apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-exporter
  namespace: postgres
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-postgres-exporter
      version: ">=8.2.0 <9.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    config:
      datasource:
        host: postgres.postgres.svc.cluster.local
        port: "5432"
        user: voize
        password: voize
        database: voize
        sslmode: disable
    serviceMonitor:
      enabled: true
      interval: 10s
      # labels expected by the variables of Grafana dashboard 9628
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: kubernetes_namespace
        - targetLabel: release
          replacement: postgres-exporter
